version: "3"
services:
  postgres:
    image: sacerdos/csapostgres:latest
    #build: ./sql/
    network_mode: bridge
    #container_name: postgres
    expose:
    - 5432
    ports:
      - 5432:5432
    volumes:
         - postgresdata:/var/lib/postgresql/data    
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=indychkov
         - POSTGRES_DB=csaproject
    restart: unless-stopped
# APP*****************************************
  springbootapp:
    image: sacerdos/csaspringbootapp:latest
    network_mode: bridge
    #container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgresdata: